# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_setting.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow_setting(object):
    def setupUi(self, MainWindow_setting):
        MainWindow_setting.setObjectName("MainWindow_setting")
        MainWindow_setting.resize(301, 208)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow_setting.setWindowIcon(icon)
        MainWindow_setting.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(MainWindow_setting)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox_CopyContent = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_CopyContent.setGeometry(QtCore.QRect(140, 90, 131, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_CopyContent.setFont(font)
        self.comboBox_CopyContent.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_CopyContent.setFrame(True)
        self.comboBox_CopyContent.setObjectName("comboBox_CopyContent")
        self.comboBox_CopyContent.addItem("")
        self.comboBox_CopyContent.addItem("")
        self.pushButton_AutoLock = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_AutoLock.setGeometry(QtCore.QRect(230, 10, 51, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_AutoLock.setFont(font)
        self.pushButton_AutoLock.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_AutoLock.setIcon(icon1)
        self.pushButton_AutoLock.setIconSize(QtCore.QSize(40, 30))
        self.pushButton_AutoLock.setFlat(True)
        self.pushButton_AutoLock.setObjectName("pushButton_AutoLock")
        self.pushButton_AutoCopy = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_AutoCopy.setGeometry(QtCore.QRect(230, 50, 51, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_AutoCopy.setFont(font)
        self.pushButton_AutoCopy.setText("")
        self.pushButton_AutoCopy.setIcon(icon1)
        self.pushButton_AutoCopy.setIconSize(QtCore.QSize(40, 30))
        self.pushButton_AutoCopy.setFlat(True)
        self.pushButton_AutoCopy.setObjectName("pushButton_AutoCopy")
        self.pushButton_MonitorClipboard = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_MonitorClipboard.setGeometry(QtCore.QRect(230, 130, 51, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_MonitorClipboard.setFont(font)
        self.pushButton_MonitorClipboard.setText("")
        self.pushButton_MonitorClipboard.setIcon(icon1)
        self.pushButton_MonitorClipboard.setIconSize(QtCore.QSize(40, 30))
        self.pushButton_MonitorClipboard.setFlat(True)
        self.pushButton_MonitorClipboard.setObjectName("pushButton_MonitorClipboard")
        MainWindow_setting.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_setting)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 301, 23))
        self.menubar.setObjectName("menubar")
        MainWindow_setting.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_setting)
        self.statusbar.setObjectName("statusbar")
        MainWindow_setting.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_setting)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_setting)

    def retranslateUi(self, MainWindow_setting):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_setting.setWindowTitle(_translate("MainWindow_setting", "设置"))
        self.label.setText(_translate("MainWindow_setting", "打开软件自动锁定"))
        self.label_2.setText(_translate("MainWindow_setting", "自动拷贝链接"))
        self.label_3.setText(_translate("MainWindow_setting", "拷贝链接类型"))
        self.label_4.setText(_translate("MainWindow_setting", "监控剪贴板"))
        self.comboBox_CopyContent.setItemText(0, _translate("MainWindow_setting", "Markdown"))
        self.comboBox_CopyContent.setItemText(1, _translate("MainWindow_setting", "Link"))

